name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo install dependencies, build package
      # Setup git credentials used for committing
      - run: git config --global user.name "GitHub Actions"
      - run: git config --global user.email "noreply@noreply.com"
      # Bump the package.json version to whatever was specified, and commit the change
      - run: npm version ${{ github.event.release.tag_name }}
      - run: git push origin HEAD:main
      - run: echo run npm publish here
